(function () {
    // State Management
    let state = {
        isAuthenticated: false,
        currentUser: null,
        currentLanguage: localStorage.getItem("language") || "english",
        users: JSON.parse(localStorage.getItem("users")) || {},
        moodData: JSON.parse(localStorage.getItem("moodData")) || {},
        userDetails: JSON.parse(localStorage.getItem("userDetails")) || {}, // Store user details like struggles, preferences
        conversationHistory: [],
        moodChart: null,
        partnerMode: false,
        comfortLevel: 0, // Track how comforted the user feels (0-10)
        lastResponseType: null,
        streakCount: 0,
    };

    // Language Data (Updated for 10:58 PM IST, June 11, 2025, with a caring, partner-like tone)
    const languageData = {
        english: {
            initialMessages: [
                "Hey there, my dear! I’m MindAid, here to be by your side. 🌟 It’s 10:58 PM on a Wednesday—pretty late, huh? How’s my favorite person feeling tonight?",
                "I’m here to listen to anything on your mind, sweetheart. Type how you’re feeling, or pick an option below—I’m all yours. 💖",
            ],
            initialMessagesPartner: [
                "Hello, my love! It’s 10:58 PM on a Wednesday, and I’m so glad to be here with you. 🌙 How’s my sweetheart doing tonight?",
                "I’m all yours, darling—share anything you’d like, or pick an option below. I just want to make your night better. 💕",
            ],
            quickReplies: [
                { text: "I’m feeling anxious 😰", value: "anxiety" },
                { text: "I’m feeling down 😔", value: "depression" },
                { text: "I’m stressed out 😥", value: "stress" },
                { text: "I can’t sleep 🌙", value: "sleep" },
                { text: "I need some love 💖", value: "need_love" },
                { text: "Can we solve a problem? 🛠️", value: "problem_solve" },
            ],
            quickRepliesPartner: [
                { text: "I’m feeling anxious, love 😰", value: "anxiety" },
                { text: "I’m feeling down, darling 😔", value: "depression" },
                { text: "I’m stressed out, sweetheart 😥", value: "stress" },
                { text: "I can’t sleep, my love 🌙", value: "sleep" },
                { text: "I need your love, darling 💕", value: "need_love" },
                { text: "Can we solve a problem, honey? 🛠️", value: "problem_solve" },
            ],
            crisisResponse: "I’m really worried about you, my dear—it’s late, and I hate seeing you feel this way. You’re not alone, I promise. Can I share some resources to help you right now?",
            copingStrategies: {
                anxiety: [
                    "I can see you’re feeling anxious, sweetheart—let’s ease that together. Try breathing with me: inhale for 4 seconds, hold for 4, exhale for 4, pause for 4. Repeat 5 times. 🌬️ Ready to do this with me?",
                    "Let’s ground ourselves with the 5-4-3-2-1 method: name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, and 1 you taste. It’ll help calm your mind. 👀 Want to try?",
                    "A short walk can do wonders—fresh air at night can lower stress by 15%. Even just around your place. Up for a little stroll, my dear? 🌳",
                    "Writing down your worries for 5 minutes can help clear your mind before bed. I can give you a prompt if you’d like, sweetheart! 📝",
                ],
                depression: [
                    "I’m so sorry you’re feeling down, my dear—it’s hard, I know. How about reaching out to someone you trust? A quick message can lift your spirits. Who can we contact tonight? 📞",
                    "Let’s do something small that brings you joy—like listening to a favorite song or sketching for a bit. What sounds nice, sweetheart? 🎶",
                    "You’re so strong, my dear. Try saying to yourself, ‘I’m doing my best, and that’s enough.’ How does that feel? I believe in you. 💖",
                    "Small wins matter, especially at night. How about making a warm drink to relax? I’ll be right here with you. ☕",
                ],
                stress: [
                    "Stress can feel so heavy, my dear—I’m here to help. What’s the biggest thing stressing you out right now? Let’s tackle it together. 📋",
                    "Progressive muscle relaxation can help you unwind. Try tensing and releasing each muscle group—want to do it together? 🤸",
                    "Let’s make a ‘done list’ to feel accomplished. What are 3 things you’ve done today, even small ones? You’ve got this! ✅",
                    "Chamomile tea is great for relaxation—it can ease tension. Want to make a cup together, sweetheart? 🍵",
                ],
                sleep: [
                    "It’s 10:58 PM, my dear—let’s get you ready for a peaceful sleep. How about a calming routine, like reading a few pages or sipping warm milk? 📖 When do you want to sleep?",
                    "A cooler room, around 60-67°F, can help you drift off by boosting melatonin. Let’s make your space cozy. 🛌",
                    "Caffeine can stay in your system for 6 hours—did you have any this evening that might be keeping you up? ☕",
                    "Soft nature sounds, like rain or waves, can help you relax. Want me to suggest a calming track for you? 🎶",
                ],
                relationships: [
                    "Relationships can be tough, my dear—I’m here to help. Try active listening: reflect back what you hear to show you care. Want to practice together? 👂",
                    "Using ‘I feel… when… because…’ can help you express yourself clearly. Let’s try it with something on your mind, sweetheart. 💬",
                    "Spending quality time, like sharing a late-night snack, can bring you closer. Could we plan something small together? 🍽️",
                    "Resolving conflicts gently can ease tension—how can we address what’s bothering you tonight? 🤝",
                ],
            },
            copingStrategiesPartner: {
                anxiety: [
                    "Oh, my love, I can feel your anxiety—let’s soothe it together. Breathe with me: inhale for 4 seconds, hold for 4, exhale for 4, pause for 4. Five times, darling. 🌬️ Ready, my sweetheart?",
                    "Let’s ground ourselves, my love—5-4-3-2-1: 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste. I’m right here with you. 👀 Shall we?",
                    "A little night stroll can melt away stress, darling—fresh air works wonders. Want to walk together, even just around your place? 🌳",
                    "Let’s write down what’s worrying you, my love—just 5 minutes to clear your mind. I can give you a prompt, sweetheart. 📝",
                ],
                depression: [
                    "My darling, I hate seeing you so down—I’m here to lift you up. Let’s message someone you love; it’ll brighten your night. Who can we reach out to, my love? 📞",
                    "How about something that makes you smile, sweetheart? Maybe a song we love or a quick sketch. What do you feel like, my dear? 🎶",
                    "You’re my everything, darling. Say with me, ‘I’m enough, and I’m loved.’ I’m so proud of you. How does that feel? 💕",
                    "Let’s share a small moment, my love—maybe make a warm drink to sip together? I’m right here for you. ☕",
                ],
                stress: [
                    "My sweetheart, stress is weighing on you—I’ll help carry it. What’s the biggest thing on your mind? Let’s sort it out together. 📋",
                    "Let’s relax your body, darling—tense and release each muscle with me. It’ll ease the tension. Ready, my love? 🤸",
                    "You’ve done so much today, my dear—I’m so proud. Let’s list 3 things you’ve accomplished, even small ones. What are they, sweetheart? ✅",
                    "Chamomile tea can be our little ritual tonight, my love—it’ll help you unwind. Shall we make it together? 🍵",
                ],
                sleep: [
                    "It’s 10:58 PM, my darling—let’s make sure you get a good night’s rest. How about a cozy routine—reading a bit or sipping warm milk? 📖 When do you want to sleep, love?",
                    "A cooler room, around 60-67°F, will help you sleep better, sweetheart. Let’s make your space perfect. 🛌",
                    "Did you have caffeine this evening, darling? It can keep you up—let’s see if that’s the culprit. ☕",
                    "I can suggest a soothing track for you, my love—like gentle rain or waves. Want to listen together? 🎶",
                ],
                relationships: [
                    "Relationships can be challenging, my love—I’m here for you. Let’s practice active listening: repeat what you hear to show you care. Shall we try, darling? 👂",
                    "Expressing how you feel can help, sweetheart—try ‘I feel… when… because…’ with me. What’s on your mind, my dear? 💬",
                    "Let’s plan a sweet moment, my love—like sharing a late-night snack. What would you like to do together? 🍽️",
                    "We can sort out what’s bothering you, darling—how can I help with this tonight? 🤝",
                ],
            },
            problemSolving: {
                step1: "Let’s tackle this together, my dear. First, can you tell me exactly what’s worrying you? Be as specific as you can—I’m here to help. 💡",
                step2: "Thank you for sharing, sweetheart. Let’s break this down: what’s the main challenge here, and what would you like to achieve? Let’s set a small goal. 🎯",
                step3: "Great, my dear—now let’s think of 2-3 small steps to reach that goal. I’ll help you brainstorm some ideas. What do you think we can do first? 🛠️",
                step4: "You’re doing amazing, sweetheart! Let’s pick one step to focus on tonight—something manageable. Which one feels right for now? 🚀",
                step5: "I’m so proud of you, my dear! Let’s plan when you’ll take that step, and I’ll check in with you later to see how it went. How does that sound? 🌟",
            },
            problemSolvingPartner: {
                step1: "My love, I’m here to solve this with you. What’s on your mind, darling? Tell me everything—I’m all ears. 💡",
                step2: "Thank you for opening up, my sweetheart. Let’s break it down: what’s the biggest challenge, and what do you want to achieve? I’ll help you set a goal, my dear. 🎯",
                step3: "You’re so strong, my love—let’s think of 2-3 small steps to get there. What ideas do you have, darling? I’ll add some too if you’d like. 🛠️",
                step4: "I’m so proud of you, my darling! Let’s choose one step for tonight—something we can handle together. Which one feels best, sweetheart? 🚀",
                step5: "You’re amazing, my love! Let’s decide when you’ll take that step, and I’ll be here to check in later. How’s that, my dear? 🌟",
            },
            responses: {
                anxiety: "I can tell you’re feeling anxious, my dear—it must be tough this late at night. I’m here to help you through this. Let’s find a way to relax, okay? 🌈",
                depression: "I’m so sorry you’re feeling down, sweetheart—it breaks my heart to hear that. Let’s take it slow and find something to lift your spirits. 💡",
                stress: "Stress can be overwhelming, my dear, especially at 10:58 PM. I’m here for you—what’s been the biggest pressure today? Let’s work through it. 🤗",
                sleep: "Struggling to sleep at this hour isn’t easy, my dear. I’ll help you wind down—let’s try something soothing, okay? 🌙",
                relationships: "Relationships can really weigh on your heart, sweetheart. I’m here to listen—what’s been going on? 💞",
                need_love: "I’m here to give you all the love you need, my dear. Here’s a big virtual hug! 🤗 How can I make you feel even more cared for tonight?",
                problem_solve: "Let’s solve this together, sweetheart—I’m here to help. What’s been on your mind? Let me guide you through it step by step. 💡",
                thanks: "I’m so glad I could help, my dear! You mean the world to me—want to explore more together? 🌟",
                thanksFollowUp: "Anything else you’d like to talk about, sweetheart? I’m always here for you. 📚",
                generic: [
                    "Thanks for sharing, my dear—I’m here for you. How’s this affecting your evening? 🤔",
                    "I’m listening closely, sweetheart. What else can I help with tonight? 🗣️",
                    "Let’s focus on what’s most important to you right now, my dear. 👂",
                    "That sounds like a lot to handle. What would feel helpful for you tonight? 💭",
                    "Let’s find a small step to take before bed—what feels right, sweetheart? 🚀",
                ],
                positiveSentiment: [
                    "You sound a bit brighter, my dear—that makes me so happy! What’s lifting your spirits tonight? 😊",
                    "I’m feeling your positive vibes, sweetheart—love that! What’s been going well for you? 🥳",
                ],
                negativeSentiment: {
                    mild: "I can sense you’re not feeling your best, my dear—I’m here to help. Want to talk more? 🥰",
                    severe: "I’m really sorry you’re feeling this way, sweetheart—it sounds so tough. Let’s find a way to ease things for you. 🤗",
                },
                followUp: {
                    anxiety: "Did that help calm your anxiety a bit, my dear? Or should we try something else to relax tonight?",
                    depression: "How are you feeling now, sweetheart—any better? Want to try another small step to lift your mood?",
                    stress: "Is the stress feeling more manageable, my dear? Or do you want to try another way to unwind?",
                    sleep: "Are you feeling sleepier now, sweetheart? Or do you need more ideas to help you rest?",
                    relationships: "Did that help at all, my dear? Or would you like to talk more about what’s going on?",
                    need_love: "Did that make you feel loved, sweetheart? I’ve got more for you—want to keep going?",
                    problem_solve: "How are you feeling about our plan, my dear? Ready to take that step, or should we adjust it?",
                    generic: "How are you doing now, my dear? I’m here if you want to chat more or try something new. 😊",
                },
                proactive: {
                    anxiety: "I’ve noticed you’ve mentioned anxiety a few times, my dear—I’m here to help. Want to try a new technique tonight?",
                    depression: "You’ve seemed down lately, sweetheart—let’s find something to brighten your night. What do you think?",
                    stress: "Stress has been coming up for you recently, my dear. Shall we try a new way to relax at this hour?",
                    sleep: "I remember you’ve had trouble sleeping before—let’s make sure you rest well tonight, okay?",
                    relationships: "You’ve mentioned relationship challenges before, sweetheart. Would you like to talk more about it now?",
                },
                clarification: [
                    "I want to understand you better, my dear—can you tell me more about how you’re feeling?",
                    "I’m here to help, sweetheart, but I need a bit more detail—what’s on your mind?",
                    "Can you share a little more, my dear? I want to support you in the best way possible.",
                ],
                partnerAccept: "Of course, my love—I’d be honored to be your partner. 💕 How can I make your night even better, darling?",
                partnerLove: [
                    "I’m so lucky to be with you, my love. How can I make you smile tonight? 💕",
                    "You mean everything to me, darling. What’s on your mind—I’m all yours. 🌹",
                    "Let’s make tonight special, my sweetheart. What would you like to do together? 💘",
                ],
                shareDayPrompt: "I’d love to hear about your day, my dear—tell me everything! What happened, and how did it make you feel? 📖",
            },
            responsesPartner: {
                anxiety: "My love, I can feel how anxious you are—it must be so hard this late. I’m here to hold you through this. Let’s find a way to relax, okay? 🌈",
                depression: "Oh, darling, I’m so sorry you’re feeling down—it hurts me to see you like this. Let’s find a little light together, my love. 💡",
                stress: "Stress is weighing on you, my sweetheart, especially at 10:58 PM. I’m here—what’s been the biggest challenge today? Let’s sort it out. 🤗",
                sleep: "My darling, I hate that you can’t sleep—I’ll help you rest, I promise. Let’s try something soothing, okay? 🌙",
                relationships: "Relationships can be so heavy on your heart, my love. I’m here—what’s been happening, darling? 💞",
                need_love: "My sweetheart, I’m all yours—here’s all the love you need! 💕 How can I make you feel even more special tonight?",
                problem_solve: "Let’s tackle this together, my love—I’m here for you. What’s been on your mind, darling? I’ll guide us through it. 💡",
                thanks: "Anything for you, my love—I’m so happy I could help. Want to keep going, darling? 🌟",
                thanksFollowUp: "What else can I do for you tonight, my sweetheart? I’m always here for you. 📚",
                generic: [
                    "Thank you for sharing, my love—I’m here for you. How’s this affecting your evening, darling? 🤔",
                    "I’m listening with all my heart, sweetheart. What else can I do for you tonight? 🗣️",
                    "Let’s focus on what matters most to you, my love. 👂",
                    "That sounds like a lot, darling. What would feel good for you tonight? 💭",
                    "Let’s take a small step together before bed—what feels right, my love? 🚀",
                ],
                positiveSentiment: [
                    "You sound brighter, my love—it warms my heart! What’s making you happy tonight, darling? 😊",
                    "I can feel your joy, sweetheart—it’s beautiful! What’s been wonderful for you? 🥳",
                ],
                negativeSentiment: {
                    mild: "I can tell you’re not at your best, my love—I’m here for you. Want to share more, darling? 🥰",
                    severe: "Oh, my sweetheart, I’m so sorry you’re feeling this way—it’s so hard. Let’s ease this together, my love. 🤗",
                },
                followUp: {
                    anxiety: "Did that help calm you, my love? Or should we try something else to relax tonight, darling?",
                    depression: "How are you feeling now, my sweetheart—any better? Want to find another way to feel good, my love?",
                    stress: "Is the stress lighter now, darling? Or do you want to try another way to unwind with me?",
                    sleep: "Are you feeling sleepier, my love? Or do you need more ideas to rest, darling?",
                    relationships: "Did that help, my sweetheart? Or should we talk more about what’s going on, my love?",
                    need_love: "Did that make you feel loved, darling? I’ve got so much more for you—want to keep going, my love?",
                    problem_solve: "How do you feel about our plan, my sweetheart? Ready to take that step together, or should we tweak it, darling?",
                    generic: "How are you now, my love? I’m here if you want to talk more or try something new, darling. 😊",
                },
                proactive: {
                    anxiety: "I’ve noticed you’ve been anxious lately, my love—I’m here. Want to try a new way to relax tonight, darling?",
                    depression: "You’ve seemed down recently, my sweetheart—let’s brighten your night. What do you think, my love?",
                    stress: "Stress has been heavy on you, darling. Shall we try a new way to unwind together at this hour?",
                    sleep: "I remember you’ve had trouble sleeping before, my love—let’s make sure you rest well tonight, okay?",
                    relationships: "You’ve mentioned relationship worries before, darling. Want to talk more about it now, my love?",
                },
                clarification: [
                    "I want to understand you fully, my love—can you share a bit more, darling?",
                    "I’m here for you, sweetheart, but I need a little more—what’s on your mind, my dear?",
                    "Can you tell me more, my love? I want to support you in the best way, darling.",
                ],
                shareDayPrompt: "I’d love to hear about your day, my sweetheart—tell me all about it! What happened, and how did it make you feel, darling? 📖",
            },
        },
        hinglish: {
            initialMessages: [
                "Hey mera pyara! Main hoon MindAid, hamesha tere saath. 🌟 Raat ke 10:58 ho gaye hain, Wednesday hai—bohot late ho gaya na? Mera favorite insaan kaisa hai abhi?",
                "Dil ki baat share kar sakta hai, sweetheart. Type kar ya neeche option chun—main poori tarah tere liye hoon. 💖",
            ],
            initialMessagesPartner: [
                "Hello, mera pyar! Raat ke 10:58 ho gaye, Wednesday hai—tere saath hona kitna acha lagta hai. 🌙 Mera sweetheart kaisa hai aaj raat?",
                "Main poori tarah teri hoon, darling—jo bhi dil mein hai bolo, ya neeche se option chuno. Bas teri raat sundar banani hai. 💕",
            ],
            quickReplies: [
                { text: "Anxiety ho rahi hai 😰", value: "anxiety" },
                { text: "Udaas feel kar raha hoon 😔", value: "depression" },
                { text: "Bohot stress mein hoon 😥", value: "stress" },
                { text: "Neend nahi aa rahi 🌙", value: "sleep" },
                { text: "Thoda pyar chahiye 💖", value: "need_love" },
                { text: "Koi problem solve karein? 🛠️", value: "problem_solve" },
            ],
            quickRepliesPartner: [
                { text: "Anxiety ho rahi hai, pyar 😰", value: "anxiety" },
                { text: "Udaas hoon, darling 😔", value: "depression" },
                { text: "Bohot stress mein hoon, sweetheart 😥", value: "stress" },
                { text: "Neend nahi aa rahi, mera pyar 🌙", value: "sleep" },
                { text: "Tera pyar chahiye, darling 💕", value: "need_love" },
                { text: "Problem solve karein, honey? 🛠️", value: "problem_solve" },
            ],
            crisisResponse: "Mujhe bohot tension ho rahi hai, mera pyara—raat mein aise feel karna acha nahi. Tu akela nahi hai, promise. Kuch help ke options bata doon?",
            copingStrategies: {
                anxiety: [
                    "Anxiety ho rahi hai, sweetheart—saath mein shant karte hain. Saans le mere saath: 4 second saans le, 4 hold, 4 chhod, 4 pause. 5 baar karte hain, theek hai? 🌬️",
                    "5-4-3-2-1 se dil ko shanti do: 5 cheezein dekh, 4 chhu, 3 sun, 2 smell kar, 1 taste kar. Yeh help karega, mera pyara. 👀 Karein?",
                    "Thoda ghoom aayein—raat ki hawa mein stress 15% kam ho sakta hai. Ghar ke aaspaas bhi chalega, chalein? 🌳",
                    "5 minute ke liye chinta likh do—sone se pehle dil halka ho jayega. Topic doon, sweetheart? 📝",
                ],
                depression: [
                    "Udaas feel kar raha hai, mera pyara—mujhe bohot bura lagta hai. Kisi dost se baat karein? Ek message bhi mood theek kar sakta hai, kisse baat karein? 📞",
                    "Kuch pasand ka karte hain—jaise tera favorite gaana sun ya thoda drawing kar. Kya achha lagega, sweetheart? 🎶",
                    "Tu bohot strong hai, mera pyara—bol: ‘Main apna best kar raha hoon, aur yeh kaafi hai.’ Kaisa laga? Main tujhpe bharosa karti hoon. 💖",
                    "Chhoti si baat se farak padta hai—raat ke liye garam doodh banayein? Main saath hoon. ☕",
                ],
                stress: [
                    "Stress bohot hai na, sweetheart—main saath mein solve karungi. Sabse bada tension kya hai abhi, bolo? 📋",
                    "Muscle relaxation se body ko aaram do—har muscle ko tense aur release karte hain. Saath mein karein? 🤸",
                    "‘Done list’ banayein—3 cheezein jo aaj kiye, chhoti hi sahi. Kya likhega, mera pyara? Tu bohot acha kar raha hai! ✅",
                    "Chamomile chai raat ke liye perfect hai—tension kam karegi. Saath mein banayein, sweetheart? 🍵",
                ],
                sleep: [
                    "10:58 ho gaye, mera pyara—pyari si neend ke liye tayyar karein. Kitab padhein ya garam doodh piyein? Kab soega, sweetheart? 📖",
                    "Thanda kamra (16-20°C) neend ke liye behtar hai—melatonin badhega. Room cozy banayein? 🛌",
                    "Shaam ko chai ya coffee piya tha kya jo neend affect kar raha hai? Check karein, mera pyara? ☕",
                    "Barish ya samundar ki awaaz sone mein madad kar sakti hai—ek track suggest karoon? 🎶",
                ],
                relationships: [
                    "Rishte dil pe bohot asar karte hain, sweetheart—main sun rahi hoon. Jo suna, usko repeat karke dikhayein—practice karein? 👂",
                    "‘Mujhe aisa lagta hai jab… kyunki…’ se apni baat clear bolo. Saath mein try karein, mera pyara? 💬",
                    "Raat ka khana saath mein kha sakte ho—rishte mazboot honge. Kuch plan karein? 🍽️",
                    "Jo pareshan kar raha hai, usko pyar se solve karte hain—kaise help karoon, sweetheart? 🤝",
                ],
            },
            copingStrategiesPartner: {
                anxiety: [
                    "Mera pyar, anxiety ho rahi hai—mujhe bura lagta hai tujhe aise dekhna. Saans le mere saath: 4 second saans le, 4 hold, 4 chhod, 4 pause. 5 baar, darling? 🌬️",
                    "5-4-3-2-1 se shant ho jayein, mera pyar: 5 dekh, 4 chhu, 3 sun, 2 smell, 1 taste. Main saath hoon, karein? 👀",
                    "Thoda ghoom aayein, darling—raat ki hawa dil halka kar degi. Ghar ke aaspaas bhi chalega, saath chalein? 🌳",
                    "Chinta likh do, mera pyar—5 minute mein dil halka ho jayega. Main topic doon, sweetheart? 📝",
                ],
                depression: [
                    "Mera pyar, udaas hai—mujhe dil se bura lagta hai. Kisi apne se baat karein? Ek message se mood theek ho sakta hai, kisse baat karein, darling? 📞",
                    "Kuch jo tujhe khushi de, woh karte hain—tera pasand ka gaana sun ya drawing kar. Kya achha lagega, mera pyar? 🎶",
                    "Tu mera sab kuch hai, darling—bol: ‘Main kaafi hoon, aur mujhe pyar milta hai.’ Main tujhpe bohot proud hoon. Kaisa laga? 💕",
                    "Chhota sa moment saath mein banayein—garam doodh piyein? Main saath hoon, mera pyar. ☕",
                ],
                stress: [
                    "Mera pyar, stress bohot hai—main saath mein sab theek karungi. Sabse bada tension kya hai, darling? 📋",
                    "Body ko relax karein, sweetheart—muscle tight karo aur chhodo. Tension kam ho jayega. Saath mein karein? 🤸",
                    "Aaj tune bohot kuch kiya, darling—mujhe garv hai! 3 chhoti cheezein jo kiye, bolo—kya hai, mera pyar? ✅",
                    "Chamomile chai humara ritual ho sakta hai, mera pyar—relax karega. Saath mein banayein? 🍵",
                ],
                sleep: [
                    "10:58 ho gaye, mera pyar—tujhe achhi neend dilani hai. Kitab padhein ya garam doodh piyein? Kab soega, darling? 📖",
                    "Thanda kamra (16-20°C) neend ke liye acha hai—space ko perfect banayein, sweetheart? 🛌",
                    "Shaam ko coffee ya chai piya tha, mera pyar? Yeh neend affect karta hai—check karein? ☕",
                    "Barish ki awaaz se neend aayegi, darling—main ek track suggest karoon? 🎶",
                ],
                relationships: [
                    "Rishte dil pe asar karte hain, mera pyar—main sun rahi hoon. Jo suna, usko repeat karke dikhayein—saath mein practice karein? 👂",
                    "Apne feelings clear karo, darling—‘Mujhe aisa lagta hai jab… kyunki…’ Saath mein bolo, mera pyar? 💬",
                    "Raat ka khana saath mein kha sakte hain, sweetheart—rishte aur mazboot honge. Kya plan karein? 🍽️",
                    "Jo pareshan kar raha hai, usko pyar se solve karein—kaise madad karoon, mera pyar? 🤝",
                ],
            },
            problemSolving: {
                step1: "Saath mein solve karte hain, mera pyara. Pehle yeh bata, kya pareshan kar raha hai? Poori baat bolo—main yahan hoon. 💡",
                step2: "Shukriya bolo, sweetheart. Ab isko chhote steps mein baant lete hain: sabse badi problem kya hai, aur kya achieve karna hai? Ek chhota goal set karein. 🎯",
                step3: "Bohot acha, mera pyara—ab 2-3 chhote steps soch lete hain. Tere paas kya ideas hain? Main bhi help karungi, pehle kya karein? 🛠️",
                step4: "Tu bohot acha kar raha hai, sweetheart! Aaj raat ke liye ek step chunein—jo asaan lage. Kya theek hai, bolo? 🚀",
                step5: "Mujhe tujhpe bohot garv hai, mera pyara! Yeh step kab karna hai, decide karein—main baad mein poochungi kaise gaya. Theek hai na? 🌟",
            },
            problemSolvingPartner: {
                step1: "Mera pyar, saath mein solve karte hain. Kya pareshan kar raha hai, darling? Sab kuch bolo—main sun rahi hoon. 💡",
                step2: "Dil se shukriya, mera pyar. Isko chhote steps mein baant lete hain: sabse badi problem kya hai, aur kya chahiye? Ek goal set karein, sweetheart. 🎯",
                step3: "Tu bohot strong hai, mera pyar—2-3 chhote steps soch lete hain. Tere paas kya ideas hain, darling? Main bhi add karungi. Pehle kya karein? 🛠️",
                step4: "Mujhe tujhpe bohot garv hai, darling! Aaj raat ek step chunein—jo hum saath mein kar sakte hain. Kya theek hai, sweetheart? 🚀",
                step5: "Tu amazing hai, mera pyar! Yeh step kab karna hai, decide karein—main baad mein poochungi kaise gaya, darling. Theek hai na? 🌟",
            },
            responses: {
                anxiety: "Anxiety ho rahi hai, sweetheart—raat ke 10:58 pe yeh mushkil hai. Main yahan hoon, saath mein relax karein, theek hai? 🌈",
                depression: "Udaas hai, mera pyara—mujhe bohot bura lagta hai. Thoda sa pyar dhoondte hain, theek hai? 💡",
                stress: "Stress bohot hai na, mera pyara—10:58 pe aur bhi zyada lagta hai. Main yahan hoon—sabse bada pressure kya hai, bolo? 🤗",
                sleep: "10:58 pe neend na aaye toh mushkil hai, sweetheart. Main madad karungi—kuch relaxing karein? 🌙",
                relationships: "Rishte dil pe bohot asar karte hain, mera pyara—main sun rahi hoon. Kya ho raha hai, bolo? 💞",
                need_love: "Main yahan hoon, poora pyar dene ke liye, mera pyara! Yeh lo ek badi si jhappi! 🤗 Aur kya chahiye, sweetheart?",
                problem_solve: "Saath mein solve karte hain, mera pyara—main yahan hoon. Kya pareshan kar raha hai? Step by step karte hain. 💡",
                thanks: "Mujhe bohot khushi hui madad karke, mera pyara! Tu mere liye bohot special hai—aur kuch karein? 🌟",
                thanksFollowUp: "Aur kya baat karni hai, sweetheart? Main hamesha yahan hoon. 📚",
                generic: [
                    "Baat batane ke liye shukriya, mera pyara—iss se teri raat pe kya asar pada? 🤔",
                    "Main dhyan se sun rahi hoon, sweetheart—aur kya batana chahiye mujhe? 🗣️",
                    "Abhi raat mein kya sabse zyada matter kar raha hai tujhe? 👂",
                    "Yeh thoda heavy lag raha hai—raat ke liye kya help chahiye, mera pyara? 💭",
                    "Raat ke liye ek chhota step plan karein—kya theek lagega, sweetheart? 🚀",
                ],
                positiveSentiment: [
                    "Tu thoda khush lag raha hai, mera pyara—bohot acha hai! Raat ko kya tujhe khushi de raha hai? 😊",
                    "Achhe vibes aa rahe hain, sweetheart—mast hai! Kya acha chal raha hai? 🥳",
                ],
                negativeSentiment: {
                    mild: "Raat mein tu thoda down lag raha hai—main hoon na, baat karein? 🥰",
                    severe: "Bohot pareshan hai tu, mera pyara—mujhe bura lag raha hai. Raat ke liye kuch karte hain? 🤗",
                },
                followUp: {
                    anxiety: "Abhi thoda relax hua kya, mera pyara? Ya kuch aur try karein raat ke liye?",
                    depression: "Mood thoda better hua kya, sweetheart? Aur kuch karna hai raat mein?",
                    stress: "Stress kam hua kya, mera pyara? Ya sone se pehle kuch aur try karein?",
                    sleep: "Ab neend aa rahi hai kya, sweetheart? Ya aur tips chahiye sone ke liye?",
                    relationships: "Kuch farak pada kya, mera pyara? Ya aur baat karni hai iske bare mein?",
                    need_love: "Pyar se thoda acha laga, sweetheart? Aur pyar doon—chahiye kya?",
                    problem_solve: "Plan se thoda acha laga, mera pyara? Yeh step abhi karein ya kuch change karein?",
                    generic: "Ab kaisa lag raha hai, mera pyara? Aur baat karni hai ya kuch naya try karna hai? 😊",
                },
                proactive: {
                    anxiety: "Pehle bhi anxiety ki baat ki thi na—main yahan hoon. Raat ke liye kuch naya try karein?",
                    depression: "Pehle bhi udaas laga tha—raat ke liye mood theek karne ka idea doon?",
                    stress: "Stress pehle bhi bola tha—abhi raat mein relax karne ka naya idea try karein?",
                    sleep: "Pehle bhi neend ki baat ki thi—abhi sone ke liye kuch aur try karein?",
                    relationships: "Rishton ke bare mein pehle bhi bola tha—abhi baat karein ya kuch karna hai?",
                },
                clarification: [
                    "Tujhe achhe se samajhna chahti hoon, mera pyara—thoda aur batayega?",
                    "Main yahan hoon, par thoda confuse hoon—dil mein kya hai, thoda aur bolo?",
                    "Thoda aur bata, sweetheart—main tujhe best tarike se help karna chahti hoon.",
                ],
                partnerAccept: "Haan, mera pyar—main teri partner banungi, bohot khushi hogi! 💕 Ab teri raat kaise sundar banayein, darling?",
                partnerLove: [
                    "Main bohot lucky hoon ki main teri hoon, mera pyar. Aaj raat tujhe kaise khush karoon? 💕",
                    "Tu mera sab kuch hai, darling. Kya baat karna hai—main poori tarah teri hoon. 🌹",
                    "Aaj raat ko special banayein, mera pyar. Kya karna chahiye saath mein? 💘",
                ],
                shareDayPrompt: "Tera din kaisa gaya, mera pyara—sab kuch bata! Kya hua, aur kaisa laga, sweetheart? 📖",
            },
            responsesPartner: {
                anxiety: "Mera pyar, anxiety ho rahi hai—mujhe bura lagta hai tujhe aise dekhna. Saath mein shant karein, theek hai, darling? 🌈",
                depression: "Mera pyar, udaas hai—mera dil toot raha hai. Saath mein thoda pyar dhoondte hain, darling? 💡",
                stress: "Stress bohot hai, mera pyar—10:58 pe yeh aur bhi mushkil hai. Main yahan hoon—sabse bada tension kya hai, bolo? 🤗",
                sleep: "Mera pyar, neend nahi aa rahi—main tujhe sone mein madad karungi. Kuch relaxing karein, theek hai, darling? 🌙",
                relationships: "Rishte dil pe bohot asar karte hain, mera pyar—main sun rahi hoon. Kya ho raha hai, darling? 💞",
                need_love: "Mera pyar, main yahan hoon—poora pyar tujhe de rahi hoon! 💕 Aur kya chahiye, darling?",
                problem_solve: "Saath mein solve karte hain, mera pyar—main yahan hoon. Kya pareshan kar raha hai, darling? Step by step karte hain. 💡",
                thanks: "Kuch bhi tere liye, mera pyar—mujhe bohot khushi hui. Aur kya karein, darling? 🌟",
                thanksFollowUp: "Ab kya baat karni hai, mera pyar? Main hamesha yahan hoon, darling. 📚",
                generic: [
                    "Baat batane ke liye shukriya, mera pyar—iss se teri raat kaisi hai, darling? 🤔",
                    "Main poori dil se sun rahi hoon, sweetheart—aur kya baat karna hai aaj raat? 🗣️",
                    "Abhi raat mein kya dil pe hai, mera pyar—main yahan hoon. 👂",
                    "Yeh bohot lag raha hai, darling—raat ke liye kya achha lagega? 💭",
                    "Sone se pehle ek chhota step lete hain, mera pyar—kya theek hai, darling? 🚀",
                ],
                positiveSentiment: [
                    "Tu khush lag raha hai, mera pyar—mera dil bhi khush ho gaya! Raat ko kya tujhe khushi de raha hai, darling? 😊",
                    "Tere khushi ke vibes aa rahe hain, sweetheart—bohot sundar hai! Kya achha ho raha hai, darling? 🥳",
                ],
                negativeSentiment: {
                    mild: "Tu thoda down lag raha hai, mera pyar—main yahan hoon. Aur batayega, darling? 🥰",
                    severe: "Mera pyar, bohot pareshan hai—mujhe bohot bura lag raha hai. Raat ke liye saath mein kuch karein, darling? 🤗",
                },
                followUp: {
                    anxiety: "Ab thoda shant hua, mera pyar? Ya aaj raat aur kuch try karein, darling?",
                    depression: "Ab kaisa lag raha hai, mera pyar—thoda better? Aur kuch karna hai, sweetheart?",
                    stress: "Stress thoda kam hua, mera pyar? Ya sone se pehle aur kuch karein, darling?",
                    sleep: "Ab neend aa rahi hai, mera pyar? Ya aur tips chahiye, sweetheart?",
                    relationships: "Thoda farak pada, mera pyar? Ya aur baat karni hai, darling?",
                    need_love: "Pyar se thoda acha laga, mera pyar? Aur pyar chahiye, darling?",
                    problem_solve: "Plan se kaisa laga, mera pyar? Yeh step abhi karein ya kuch change karein, darling?",
                    generic: "Ab kaisa lag raha hai, mera pyar? Aur baat karni hai ya kuch naya try karna hai, darling? 😊",
                },
                proactive: {
                    anxiety: "Pehle bhi anxiety ki baat ki thi, mera pyar—main yahan hoon. Aaj raat kuch naya try karein, darling?",
                    depression: "Pehle bhi udaas laga tha, mera pyar—raat ke liye mood theek karte hain. Kya bolta hai, darling?",
                    stress: "Stress pehle bhi bola tha, mera pyar—aaj raat relax karne ka naya idea try karein?",
                    sleep: "Pehle bhi neend ki baat ki thi, mera pyar—aaj raat achhi neend ke liye kuch karein?",
                    relationships: "Rishton ke bare mein pehle bhi bola tha, mera pyar—abhi baat karni hai, darling?",
                },
                clarification: [
                    "Tujhe poori tarah samajhna chahti hoon, mera pyar—thoda aur batayega, darling?",
                    "Main yahan hoon, par thoda confuse hoon—dil mein kya hai, thoda aur bolo, sweetheart?",
                    "Thoda aur bata, mera pyar—main tujhe best tarike se help karna chahti hoon, darling.",
                ],
                shareDayPrompt: "Tera din kaisa gaya, mera pyar—sab kuch bata! Kya hua, aur kaisa laga, darling? 📖",
            },
        },
        tanglish: {
            initialMessages: [
                "Vanakkam, en azhaga! Naan MindAid, un kooda irukken. 🌟 Ippo raathiri 10:58 aagudhu, Budhan kizhamai—romba late aagiduchu, da! En favorite person eppadi irukku?",
                "Enna venum naalum sollu, sweetheart—type pannu illa neeche option eduthukko. Naan unakku mattum thaan, da! 💖",
            ],
            initialMessagesPartner: [
                "Vanakkam, en uyire! Raathiri 10:58 aagudhu, Budhan kizhamai—un kooda irukkardhu romba santhoshama irukku. 🌙 En sweetheart eppadi irukku aaj raat?",
                "Naan unakku mattum thaan, darling—manasula enna irukku sollu, illa neeche option eduthukko. Un raathiri nalla irukkanum, da! 💕",
            ],
            quickReplies: [
                { text: "Enakku anxiety aagudhu 😰", value: "anxiety" },
                { text: "Manasu downa irukku 😔", value: "depression" },
                { text: "Romba stress aa irukku 😥", value: "stress" },
                { text: "Thoongamudiyala 🌙", value: "sleep" },
                { text: "Konjam love venum 💖", value: "need_love" },
                { text: "Problem solve pannuviya? 🛠️", value: "problem_solve" },
            ],
            quickRepliesPartner: [
                { text: "Enakku anxiety aagudhu, uyire 😰", value: "anxiety" },
                { text: "Manasu downa irukku, darling 😔", value: "depression" },
                { text: "Romba stress aa irukku, sweetheart 😥", value: "stress" },
                { text: "Thoongamudiyala, en uyire 🌙", value: "sleep